# Numpy

In [2]:
import numpy as np

 ## The Basics 

In [4]:
# 1D array
a = np.array([1,2,3])
a # array([1, 2, 3])

print(a) # [1 2 3]

[1 2 3]


In [5]:
# 2D array
b = np.array([[9.0,8.0,7.0], [6.0,5.0,4.0]])
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [8]:
# Get Dimentions
a.ndim # 1
b.ndim # 2

2

In [11]:
# Get Shape
a.shape # (3,)
b.shape # (2, 3)

(2, 3)

In [13]:
# Get Type
a.dtype # dtype('int64')
b.dtype # dtype('float64')

dtype('float64')

In [16]:
a = np.array([1,2,3], dtype='int16')
a.dtype # dtype('int16')

dtype('int16')

In [17]:
# Get item's size in byte
a.itemsize # 2, mean 16 bits

2

In [19]:
# to get number of elements, we use size method
a.size # 3
b.size # 6

6

In [22]:
# to got total size of all items
a.size * a.itemsize # 6

# same as nbytes
a.nbytes # 6

6

## Accessing/Changing Specific Elements, Rows, Columns, etc (slicing)

In [23]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])

a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [25]:
a.shape

(2, 7)

In [27]:
# Get a specific element [r, c]
a[1, 3] # np.int64(11)

np.int64(11)

In [29]:
# same as lists we can use nigative index, that count from end
a[1, -4] # np.int64(11)

np.int64(11)

In [30]:
# to got a row
a[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

In [31]:
# column
a[:, 3]

array([ 4, 11])

In [36]:
# specify also the step size [startindex: endindex(excluded): stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [37]:
a[0, 6:0:-2]

array([7, 5, 3])

In [38]:
# change an item's value
a[0,3] = 5
a

array([[ 1,  2,  3,  5,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [41]:
# change a column's values
a[:, 5] = 5
a

array([[ 1,  2,  3,  5,  5,  5,  4],
       [ 8,  9, 10, 11, 12,  5,  4]])

In [42]:
a[:, 5] = [2, 1]
a

array([[ 1,  2,  3,  5,  5,  2,  4],
       [ 8,  9, 10, 11, 12,  1,  4]])

- 3D examlpe

In [5]:
b = np.array([[[1,2], [3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [6]:
# Get a specific element 
b[0, 1, 0] # np.int64(3)

np.int64(3)

In [7]:
b[:, 1, :]

array([[3, 4],
       [7, 8]])

In [9]:
# replace
b[:, 1, :] = np.array([[5,5], [2,2]])
b

array([[[1, 2],
        [5, 5]],

       [[5, 6],
        [2, 2]]])

In [10]:
b[:, 1, :] = np.array([[5,5,11], [2,2]]) # give error
b

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

## Initializing Different Types of Arrays

In [12]:
# All zeros matrix
np.zeros((2,3)) # give the shape

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.zeros((2,3,2,5)) 

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [15]:
# ALl ones matrix
np.ones(4) # same give the shape

array([1., 1., 1., 1.])

In [16]:
np.ones((2,5,7))

array([[[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]]])

In [17]:
# also we can spicify the data type
np.ones((2,5,7), dtype='int16')

array([[[1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1]]], dtype=int16)

In [18]:
# Any other number, spicify the shape, then the value to fill
np.full((3,3), 55) # default data type is int, but we can change

array([[55, 55, 55],
       [55, 55, 55],
       [55, 55, 55]])

In [20]:
np.full((3,3), 55, dtype='float32')

array([[55., 55., 55.],
       [55., 55., 55.],
       [55., 55., 55.]], dtype=float32)

In [24]:
# Any other number (full_like)
# generate array like a shape
np.full_like(a, 10)

array([[10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10]])

In [25]:
# we can make the same with full by use a.shape instead of a
np.full(a.shape, 44)

array([[44, 44, 44, 44, 44, 44, 44],
       [44, 44, 44, 44, 44, 44, 44]])

In [28]:
# Generate random decimal numbers
np.random.rand(4,4) # add the shape

array([[0.42201739, 0.73874381, 0.67478332, 0.05135843],
       [0.62707012, 0.5423661 , 0.28626864, 0.60132698],
       [0.14116786, 0.13467276, 0.16723831, 0.03657996],
       [0.75799914, 0.83336998, 0.56963012, 0.08351981]])

In [29]:
np.random.rand(4,4,2)

array([[[0.41736311, 0.88376575],
        [0.81057483, 0.87600315],
        [0.06365956, 0.52886887],
        [0.555977  , 0.40251124]],

       [[0.19992122, 0.23808746],
        [0.99701116, 0.06839001],
        [0.36995191, 0.07473788],
        [0.42198543, 0.72756953]],

       [[0.2726709 , 0.18923944],
        [0.52109866, 0.88028406],
        [0.90220312, 0.45371653],
        [0.6875629 , 0.93678359]],

       [[0.96516069, 0.74595039],
        [0.7080768 , 0.59038062],
        [0.36217955, 0.03434326],
        [0.61750939, 0.98201611]]])

In [30]:
# to make like a shape, we have to use random_sample
np.random.random_sample(a.shape)

array([[0.31870531, 0.64929969, 0.7354209 , 0.09933954, 0.55478135,
        0.34131124, 0.41515155],
       [0.76081557, 0.88509309, 0.40444621, 0.07233152, 0.75859666,
        0.82848336, 0.23637097]])

In [33]:
# to generate array with int values
np.random.randint(9, size=(3,3)) # first spicify the range, then the shape

array([[1, 0, 6],
       [6, 2, 3],
       [8, 4, 8]], dtype=int32)

In [35]:
# to make range from to
np.random.randint(3,9, size=(3,3))

array([[7, 6, 7],
       [4, 7, 8],
       [7, 8, 7]], dtype=int32)

In [36]:
# we also can build an identity matrix using np
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
# we can repeat values from array
arr = np.array([1,2,3])
r = np.repeat(arr,5)
r

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3])

In [39]:
arr = np.array([[1,2,3]])
r = np.repeat(arr,5, axis=0)
r

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

## Question 1:
generate array: <br>
1  1  1  1  1 <br>
1  0  0  0  1 <br>
1  0  9  0  1 <br>
1  0  0  0  1 <br>
1  1  1  1  1 <br>

In [40]:
output = np.ones((5,5))
output

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [41]:
z = np.zeros((3,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [43]:
z[1,1] = 9
z

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [44]:
output[1:4, 1:4] = z
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### Be careful when copying arrays!!!

In [45]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [46]:
b = a
b

array([1, 2, 3])

In [47]:
b[0] = 100
print(b)
print(a)

[100   2   3]
[100   2   3]


In [49]:
a = np.array([1,2,3])
b = a.copy()

b[0] = 100

print(b)
print(a)

[100   2   3]
[1 2 3]


In [50]:
## Mathematics 
a = np.array([1,2,3,4])
a + 2

array([3, 4, 5, 6])

In [52]:
a - 2

array([-1,  0,  1,  2])

In [53]:
a * 2

array([2, 4, 6, 8])

In [54]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [56]:
a = np.array([1,2,3,4])
b = np.array([1,0,1,0])

a + b

array([2, 2, 4, 4])

In [57]:
a ** 2

array([ 1,  4,  9, 16])

In [58]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [59]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### Linear Algebra

In [4]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
b = np.full((3,2), 2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [7]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

### Statistics

In [8]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
np.min(stats)

np.int64(1)

In [10]:
np.max(stats)

np.int64(6)

In [11]:
np.min(stats, axis=1)

array([1, 4])

## Reorganizing Arrays 

In [12]:
before = np.array([[1,2,3,4], [5,6,7,8]])
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
after = before.reshape((8,1))
after

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [16]:
after = before.reshape((4,2))
after

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [17]:
after = before.reshape((2,2,2))
after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [18]:
after = before.reshape((2,3))
after

ValueError: cannot reshape array of size 8 into shape (2,3)

In [20]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
np.vstack([v1,v2,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [22]:
# Horizontal

np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

### Load data in from a file

In [24]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [26]:
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

### Advanced Indexing and Boolean Masking

In [28]:
filedata > 55

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [30]:
filedata[filedata > 55]

array([196,  75, 766,  75, 999,  78,  76,  88], dtype=int32)

In [31]:
a = np.array([1,2,3,4,5,6,7,8])
a[[1,3,7]]

array([2, 4, 8])

In [32]:
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [33]:
np.all(filedata > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [34]:
np.all(filedata > 50, axis=1)

array([False, False, False])

In [35]:
np.any(filedata > 50, axis=1)

array([ True,  True,  True])

In [39]:
(filedata > 50) & (filedata < 100)

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])